spring:
  application:
    name: main_securesync
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/securesync_db?serverTimezone=Asia/Seoul
    username: ss_admin
    password: ss_pass123!

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
  jwt:
    secret: your-very-long-and-secure-random-secret-key-must-be-at-least-32-chars-long-example
    expiration: 86400000
  main:
    allow-bean-definition-overriding: true
  logging:
    level:
      org.springframework.messaging: TRACE
      org.springframework.web.socket: TRACE
  jasypt:
    encryptor:
      password: "SyncSecureKey!@#"
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB


file:
  notice-upload-dir: /home/ubuntu/uploads/notices/
  document-upload-dir: /home/ubuntu/uploads/documents/